// <auto-generated />
using System;
using CarRent.Models.DBModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarRent.Migrations
{
    [DbContext(typeof(carrentContext))]
    [Migration("20210216115431_AddedReservationEntity")]
    partial class AddedReservationEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CarRent.CarManagement.Domain.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .HasColumnName("brand")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("CarClassDescription");

                    b.Property<string>("Typ")
                        .HasColumnName("typ")
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id");

                    b.HasIndex("CarClassDescription");

                    b.ToTable("car");
                });

            modelBuilder.Entity("CarRent.CarManagement.Domain.CarClass", b =>
                {
                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("description");

                    b.Property<decimal>("Price")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 38, scale: 17)))
                        .HasColumnName("price")
                        .HasColumnType("decimal");

                    b.HasKey("Description");

                    b.ToTable("carclass");

                    b.HasData(
                        new
                        {
                            Description = "Einfachklasse",
                            Price = 13.5m
                        },
                        new
                        {
                            Description = "Mittelklasse",
                            Price = 20.6m
                        },
                        new
                        {
                            Description = "Luxusklasse",
                            Price = 35.45m
                        });
                });

            modelBuilder.Entity("CarRent.CustomerManagement.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnName("address")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id");

                    b.ToTable("customer");
                });

            modelBuilder.Entity("CarRent.ReservationManagement.Domain.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("CarId");

                    b.Property<int>("CustomerId");

                    b.Property<DateTime>("EndDate")
                        .HasColumnName("enddate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Price")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 38, scale: 17)))
                        .HasColumnName("price")
                        .HasColumnType("decimal");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("startdate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("CustomerId");

                    b.ToTable("reservation");
                });

            modelBuilder.Entity("CarRent.CarManagement.Domain.Car", b =>
                {
                    b.HasOne("CarRent.CarManagement.Domain.CarClass", "CarClass")
                        .WithMany("Cars")
                        .HasForeignKey("CarClassDescription");
                });

            modelBuilder.Entity("CarRent.ReservationManagement.Domain.Reservation", b =>
                {
                    b.HasOne("CarRent.CarManagement.Domain.Car", "Car")
                        .WithMany("Reservations")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CarRent.CustomerManagement.Domain.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
